### ISSUE TITLE
'screenshotMaker' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by iOSDevil** [gualtierofrigerio/ScreenshotSwiftUI#1]
Hi,

I've implemented as per the instructions:
`Import ScreenshotSwiftUI

struct MyView: View 
    var body: some View {
        VStack {
            Text("Hello world")
        }.screenshotMaker { screenshotMaker in 
            let uiImage = screenshotMaker.screenshot()
        }   
    }`

I get the above error.

Are there more steps required in terms of setup?

Thanks

**Comment by gualtierofrigerio** [comment]
My bad... I forgot to add the change that made the function screenshotMaker public, try updating to 0.3.0

**Comment by andrewstephenson-v1** [comment]
Thanks! Confirming the issue can be resolved.
